services:
  - type: web
    name: roxy-store-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: UANGX_WEBHOOK_PATH
        value: /webhook/uangx
